api_platform:
  title: API MelodayzMusic App
  version: 1.0.0
  enable_docs: true
  enable_entrypoint: true

  defaults:
    security: null # Esorina aloha ny authentication
    stateless: true # Tsy hitahiry session (mila JWT raha apetraka authentication)
    cache_headers:
      vary: ["Content-Type", "Authorization", "Origin"]
    pagination_client_enabled: true # Ahafahana mandefa page & limit amin'ny query params
    pagination_client_items_per_page: true # Ahafahana mametraka `itemsPerPage`

  swagger:
    versions: [3] # Swagger OpenAPI v3 support
    api_keys:
      JWT:
        name: Authorization
        type: header

  formats:
    jsonld:
      mime_types: ["application/ld+json"]
    json:
      mime_types: ["application/json"]
    html:
      mime_types: ["text/html"]
    multipart:
      mime_types: ["multipart/form-data"] # Ahafahana mandefa form file
    jsonmergepatch:
      mime_types: ["application/merge-patch+json"] # Ahafahana mandefa form file

  mapping:
    paths:
      - "%kernel.project_dir%/src/Document" # Hikarohana entités MongoDB

  exception_to_status:
    Symfony\Component\Security\Core\Exception\AccessDeniedException: 403
    Symfony\Component\Routing\Exception\ResourceNotFoundException: 404
