lexik_jwt_authentication:
    secret_key: '%env(resolve:JWT_SECRET_KEY)%'
    public_key: '%env(resolve:JWT_PUBLIC_KEY)%'
    pass_phrase: '%env(JWT_PASSPHRASE)%'
    # ity dia ny expiration date an'ny token
    # raha tsy apetraka dia ho 1 ora ny expiration date
    # raha apetraka dia ho 1 taona ny expiration date
    token_ttl: 31536000
    token_extractors:
        authorization_header:
            # ity dia ny header an'ny token
            enabled: true
            prefix: Bearer
            name: Authorization

